### ISSUE TITLE
export/importができない

### ISSUE THREAD

**Issue by gamesukimanIRS** [itsu020402/WorldEditorEX#3]
いつもこのWorldEditを利用させてもらっております。

Export/Importの機能を試そうと、/export testでエクスポートし、/import testでインポートを試みました。
すると、一応画面では「処理が完了しました」と出てくるのですが、

```
20:08:24 [CRITICAL] コマンド'import 'をimportで実行中に、処理できない例外が発生：java.lang.ArrayIndexOutOfBoundsException: 0
        at itsu.mcpe.WorldEditorEX.WorldEditorEX.onCommand(WorldEditorEX.java:337)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:247)
        at cn.nukkit.Server.dispatchCommand(Server.java:688)
        at cn.nukkit.Player.handleDataPacket(Player.java:2622)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:2022)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1074)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:508)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)

20:08:24 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 0
        at itsu.mcpe.WorldEditorEX.WorldEditorEX.onCommand(WorldEditorEX.java:337)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:247)
        at cn.nukkit.Server.dispatchCommand(Server.java:688)
        at cn.nukkit.Player.handleDataPacket(Player.java:2622)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:2022)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1074)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:508)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
```

と出てきて/pasteしても何も出現しませんでした。

その後、test.jsonファイルを開くと、中身は{}のまま何もない状態で、エラーも出ておらず普通に空っぽの状態でした。

以上、報告しておきます

**Comment by itsu020402** [comment]
/exportの前に/copyする必要があります。
概念的にはpcのクリップボードへコピーでふ。
